//Create tables and contraints
CREATE TABLE CAMP
  (
    CampID      INTEGER NOT NULL,
    Description VARCHAR(20) ,
    MaxPerson   INTEGER NOT NULL ,
    Available BOOLEAN
  ) ; 
ALTER TABLE CAMP ADD CONSTRAINT CAMP_PK PRIMARY KEY ( CampID ) ;


CREATE TABLE CAMPING_RES
  (
    CampRes_No           INTEGER NOT NULL ,
    Start_Date           DATE NOT NULL ,
    End_Date             DATE NOT NULL ,
    E_ACCOUNT_Account_ID INTEGER NOT NULL ,
    CAMP_CampID          INTEGER NOT NULL ,
    E_Acount_ID          INTEGER NOT NULL
  ) ;
ALTER TABLE CAMPING_RES ADD CONSTRAINT CAMPING_RES_PK PRIMARY KEY ( CampRes_No ) ;


CREATE TABLE E_ACCOUNT
  (
    RFID_Code                   INTEGER NOT NULL ,
    Balance                     DECIMAL (10,3) NOT NULL ,
    PARTICIPANTS_Participant_ID INTEGER NOT NULL ,
    E_mail                    VARCHAR (30) NOT NULL ,
    E_Acount_ID                 INTEGER NOT NULL ,
    First_Name                  VARCHAR (50) NOT NULL ,
    Last_Name                   VARCHAR (50) NOT NULL ,
    Email                       VARCHAR (50) NOT NULL ,
    Phone                       CHAR (20) ,
    Payment_Status BOOLEAN NOT NULL ,
    Pay_InAdvance BOOLEAN NOT NULL
  ) ;
  ALTER TABLE E_ACCOUNT ADD CONSTRAINT E_ACCOUNT_PK PRIMARY KEY ( E_Acount_ID ) ;

CREATE TABLE FOOD
  (
    Food_ID       INTEGER NOT NULL ,
    Food_Name     VARCHAR (100) NOT NULL ,
    Food_Quantity INTEGER NOT NULL ,
    Food_Price    DECIMAL (6,2) NOT NULL
  ) ;
ALTER TABLE FOOD ADD CONSTRAINT FOOD_PK PRIMARY KEY ( Food_ID ) ;

CREATE TABLE F_INVOICE
  (
    Food_InvoiceID       INTEGER NOT NULL ,
    SoldDate             DATE NOT NULL ,
    E_Acount_ID          INTEGER NOT NULL
  ) ;
ALTER TABLE F_INVOICE ADD CONSTRAINT F_INVOICE_PK PRIMARY KEY ( Food_InvoiceID ) ;

CREATE TABLE FOOD_INVOICE
  (
    Quantity_Sold       INTEGER NOT NULL ,
    Food_InvoiceID   	INTEGER NOT NULL ,
    Food_ID             INTEGER NOT NULL
  ) ;
ALTER TABLE FOOD_INVOICE ADD CONSTRAINT FOOD_INVOICE_PK PRIMARY KEY ( Food_InvoiceID , Food_ID );

CREATE TABLE GROUPMEMBERS
  (
    GroupID                   INTEGER NOT NULL ,
    E_mail                    VARCHAR(30) NOT NULL ,
    Co_email                  VARCHAR(20) NOT NULL ,
    CampRes_No                INTEGER NOT NULL ,
    Check_in BOOLEAN NOT NULL
  ) ;
ALTER TABLE GROUPMEMBERS ADD CONSTRAINT GROUP_PK PRIMARY KEY ( GroupID, Co_email ) ;

CREATE TABLE MATERIAL
  (
    Material_ID       INTEGER NOT NULL ,
    Name              VARCHAR (200) NOT NULL ,
    Deposit_Amount    DECIMAL (10,3) NOT NULL ,
    Loaning_Price     DECIMAL (10,3) NOT NULL ,
    Description       VARCHAR (50) ,
    Material_Quantity INTEGER NOT NULL
  ) ;
ALTER TABLE MATERIAL ADD CONSTRAINT MATERIAL_PK PRIMARY KEY ( Material_ID ) ;

CREATE TABLE M_INVOICE
  (
    Material_InvoiceID   INTEGER NOT NULL ,
    Start_Date           DATE NOT NULL ,
    End_Date             DATE ,
    E_ACCOUNT_Account_ID INTEGER NOT NULL ,
    E_Acount_ID          INTEGER NOT NULL
  ) ;
ALTER TABLE M_INVOICE ADD CONSTRAINT M_INVOICE_PK PRIMARY KEY ( Material_InvoiceID ) ;

CREATE TABLE MATERIAL_INVOICE
  (
    Material_Quantity            INTEGER NOT NULL ,
    Material_ID         INTEGER NOT NULL ,
    Material_InvoiceID INTEGER NOT NULL
  ) ;
ALTER TABLE MATERIAL_INVOICE ADD CONSTRAINT MATERIAL_INVOICE_PK PRIMARY KEY ( Material_ID, Material_InvoiceID ) ;


//Foreign keys
ALTER TABLE CAMPING_RES ADD CONSTRAINT CAMPING_RES_CAMP_FK FOREIGN KEY ( CAMP_CampID ) REFERENCES CAMP ( CampID ) ;

ALTER TABLE CAMPING_RES ADD CONSTRAINT CAMPING_RES_E_ACCOUNT_FK FOREIGN KEY ( E_Acount_ID ) REFERENCES E_ACCOUNT ( E_Acount_ID ) ;

ALTER TABLE FOOD_INVOICE ADD CONSTRAINT FOOD_INVOICE_FOOD_FK FOREIGN KEY ( Food_ID ) REFERENCES FOOD ( Food_ID ) ;

ALTER TABLE FOOD_INVOICE ADD CONSTRAINT FOOD_INVOICE_F_INVOICE_FK FOREIGN KEY (Food_InvoiceID ) REFERENCES F_INVOICE ( Food_InvoiceID) ;

ALTER TABLE F_INVOICE ADD CONSTRAINT F_INVOICE_E_ACCOUNT_FK FOREIGN KEY ( E_Acount_ID ) REFERENCES E_ACCOUNT ( E_Acount_ID ) ;

ALTER TABLE GROUPMEMBERS ADD CONSTRAINT GROUP_CAMPING_RES_FK FOREIGN KEY ( CampRes_No) REFERENCES CAMPING_RES ( CampRes_No ) ;

ALTER TABLE GROUPMEMBERS ADD CONSTRAINT GROUP_ACCOUNT_EMAIL_FK FOREIGN KEY ( E_mail ) REFERENCES E_ACCOUNT( E_mail) ; -- It's not working

ALTER TABLE GROUPMEMBERS ADD CONSTRAINT GROUP_CAMP_RES_FK FOREIGN KEY (CampRes_No  ) REFERENCES CAMPING_RES( CampRes_No ) ;

ALTER TABLE MATERIAL_INVOICE ADD CONSTRAINT MATERIAL_INVOICE_MATERIAL_FK FOREIGN KEY ( Material_ID ) REFERENCES MATERIAL ( Material_ID ) ;

ALTER TABLE MATERIAL_INVOICE ADD CONSTRAINT MATERIAL_INVOICE_M_INVOICE_FK FOREIGN KEY ( Material_InvoiceID ) REFERENCES M_INVOICE ( Material_InvoiceID ) ;

ALTER TABLE M_INVOICE ADD CONSTRAINT M_INVOICE_E_ACCOUNT_FK FOREIGN KEY ( E_Acount_ID ) REFERENCES E_ACCOUNT ( E_Acount_ID ) ;

//Insert data into Camp Table
INSERT INTO Camp(CampID, Description, MaxPerson, Available)
VALUES (1,'', 5, 0);
INSERT INTO Camp(CampID, Description, MaxPerson, Available)
VALUES (2,'Near by river', 4, 0);